#!/usr/bin/env php
<?php
/**
 * Starter.php
 *
 * Version:     1.1.0
 * Author:      James John McGuire
 * Author URI:  http://www.digitalzenworks.com/
 * PHP version  8.1.1
 *
 * @category  PHP
 * @package   ConsumerProvider
 * @author    James John McGuire <jamesjohnmcguire@gmail.com>
 * @copyright 2021 - 2026 James John McGuire <jamesjohnmcguire@gmail.com>
 * @license   MIT https://opensource.org/licenses/MIT
 * @link      https://github.com/jamesjohnmcguire/consumer-provider
 */

declare(strict_types=1);

namespace digitalzenworks\ConsumerProvider;

require_once __DIR__ . '/SourceCode/Processor.php';

set_time_limit(0);

$providers = [];
$consumers = [];

if (PHP_SAPI === 'cli')
{
	if (empty($argv[1]) === false)
	{
		$provider = $argv[1];
		$providers[] = $provider;
	}

	if (empty($argv[2]) === false)
	{
		$consumer = $argv[2];
		$consumers[] = $consumer;
	}
}
else
{
	if ((empty($_GET) === false) && (empty($_GET['provider']) === false))
	{
		$provider = $_GET['provider'];
		$providers[] = $provider;
	}

	if ((empty($_GET) === false) && (empty($_GET['consumer']) === false))
	{
		$consumer = $_GET['consumer'];
		$consumers[] = $consumer;
	}
}

$processor = new Processor($providers, $consumers);

$processor->process();
